[package]
name = "exchange"
version = "0.1.0"
authors = ["HOANGDUONG\\HoangDuong1607 <hoangduong1607@gmail.com>"]

[dependencies]
time = "0.1.37"
linked-hash-map = "0.4.2"
serde_json = "1.0.2"
serde_derive = "1.0"
serde = "1.0.9"